export type ColumnType = "text" | "numeric" | "date";

export type SheetColumnMapping = {
  column: string;
  type: ColumnType;
  sourceAliases?: string[];
};

export type SheetMapping = {
  sheetName: string;
  tableName: string;
  columns: SheetColumnMapping[];
};

export const sheetMappings: SheetMapping[] = [
  {
    sheetName: "bridge_so_line",
    tableName: "o2.raw_bridge_so_line",
    columns: [
      { column: "so_no_doc", type: "text", sourceAliases: ["SO_NO_MAP"] },
      { column: "fac_line", type: "text" },
    ],
  },
  {
    sheetName: "data_3party",
    tableName: "o2.raw_data_3party",
    columns: [
      { column: "date", type: "date" },
      { column: "line", type: "text" },
      { column: "style", type: "text" },
      { column: "so_no", type: "text" },
      { column: "color", type: "text" },
      { column: "audit", type: "text" },
      { column: "total", type: "numeric" },
      { column: "percent", type: "numeric" },
      { column: "code", type: "text" },
      { column: "defect_qty", type: "numeric", sourceAliases: ["defectqty"] },
      { column: "fac_line", type: "text" },
      { column: "st", type: "text" },
      { column: "so_year", type: "text" },
      { column: "so_no_doc", type: "text", sourceAliases: ["SO_NO_MAP"] },
      { column: "week", type: "text" },
      { column: "inspect_qty", type: "numeric", sourceAliases: ["inspet_qty"] },
    ],
  },
  {
    sheetName: "data_endline",
    tableName: "o2.raw_data_endline",
    columns: [
      { column: "so_no_doc", type: "text", sourceAliases: ["SO_NO_MAP"] },
      { column: "fac_line", type: "text" },
      { column: "total_inspect", type: "numeric" },
      { column: "job_date", type: "date" },
      { column: "location_code", type: "text" },
      { column: "defect_code", type: "text" },
      { column: "line_name", type: "text" },
      { column: "so_no", type: "text" },
      { column: "so_year", type: "text" },
      { column: "good_qty", type: "numeric" },
      { column: "order_qty", type: "numeric" },
      { column: "defect_point", type: "numeric" },
    ],
  },
  {
    sheetName: "data_final",
    tableName: "o2.raw_data_final",
    columns: [
      { column: "factory", type: "text" },
      { column: "date", type: "date" },
      { column: "so_year", type: "text" },
      { column: "so_no", type: "text" },
      { column: "style_no", type: "text" },
      { column: "pro_type", type: "text" },
      { column: "cust_code", type: "text" },
      { column: "sewing_line_no", type: "text" },
      { column: "type_of_inspection", type: "text" },
      { column: "inspected_by", type: "text" },
      { column: "order_quantity_pcs", type: "numeric" },
      { column: "total_garment_inspected", type: "numeric" },
      { column: "result", type: "text" },
      { column: "total_defect_found", type: "numeric" },
      { column: "defect_rate", type: "numeric" },
      { column: "defect_code", type: "text" },
      { column: "defect_desc", type: "text" },
      { column: "defect_qty", type: "numeric" },
      { column: "so_no_doc", type: "text" },
      { column: "fac_line", type: "text" },
      { column: "color", type: "text" },
      { column: "customer_brand", type: "text" },
    ],
  },
  {
    sheetName: "data_fn_fg",
    tableName: "o2.raw_data_fn_fg",
    columns: [
      { column: "bu_id", type: "text" },
      { column: "step", type: "text" },
      { column: "so_no_doc", type: "text" },
      { column: "cust_name", type: "text" },
      { column: "style_code", type: "text" },
      { column: "sam_prod", type: "numeric" },
      { column: "trx_date", type: "date" },
      { column: "qty", type: "numeric" },
      { column: "total_min", type: "numeric" },
      { column: "factory", type: "text" },
    ],
  },
  {
    sheetName: "data_inline",
    tableName: "o2.raw_data_inline",
    columns: [
      { column: "total_inspect", type: "numeric" },
      { column: "job_date", type: "date" },
      { column: "id_bu", type: "text" },
      { column: "line_no", type: "text" },
      { column: "so_no", type: "text" },
      { column: "so_year", type: "text" },
      { column: "defect_desc_eng", type: "text" },
      { column: "cnt_failed", type: "numeric" },
      { column: "fac_line", type: "text" },
      { column: "defect_code", type: "text" },
      { column: "so_no_doc", type: "text" },
    ],
  },
  {
    sheetName: "data_prefinal",
    tableName: "o2.raw_data_prefinal",
    columns: [
      { column: "location_code", type: "text" },
      { column: "line_name", type: "text" },
      { column: "job_date", type: "date" },
      { column: "so_no", type: "text" },
      { column: "so_year", type: "text" },
      { column: "defect_codes", type: "text" },
      { column: "fac_line", type: "text" },
      { column: "total_defects", type: "numeric" },
      { column: "defect_descs", type: "text" },
      { column: "so_no_doc", type: "text" },
      { column: "order_qty", type: "numeric" },
      { column: "total_inspect", type: "numeric" },
    ],
  },
  {
    sheetName: "Defect Qty",
    tableName: "o2.raw_defect_qty",
    columns: [
      { column: "parameter", type: "text" },
      { column: "parameter_fields", type: "text" },
      { column: "parameter_order", type: "numeric" },
    ],
  },
  {
    sheetName: "Defect Rate",
    tableName: "o2.raw_defect_rate",
    columns: [
      { column: "defect_rate", type: "text" },
      { column: "defect_rate_fields", type: "text" },
      { column: "defect_rate_order", type: "numeric" },
    ],
  },
  {
    sheetName: "mt_defect",
    tableName: "o2.raw_mt_defect",
    columns: [
      { column: "defect_code", type: "text" },
      { column: "defect_grp_code", type: "text" },
      { column: "defect_desc_thai", type: "text" },
      { column: "defect_desc_eng", type: "text" },
      { column: "defect_desc_vi", type: "text" },
      { column: "defect_grp_problem", type: "text" },
      { column: "type_top", type: "text" },
      { column: "type_bottom", type: "text" },
      { column: "color", type: "text" },
      { column: "active", type: "text" },
    ],
  },
  {
    sheetName: "mt_department",
    tableName: "o2.raw_mt_department",
    columns: [
      { column: "location_code", type: "text" },
      { column: "line_name", type: "text" },
      { column: "sub_department", type: "text" },
      { column: "department_head", type: "text" },
      { column: "fac_line", type: "text" },
    ],
  },
  {
    sheetName: "mt_factory",
    tableName: "o2.raw_mt_factory",
    columns: [
      { column: "factory", type: "text" },
      { column: "index", type: "numeric" },
      { column: "bu", type: "text" },
      { column: "factoryg", type: "text" },
      { column: "factory_fi", type: "text" },
    ],
  },
  {
    sheetName: "mt_so",
    tableName: "o2.raw_mt_so",
    columns: [
      { column: "so_no_doc", type: "text", sourceAliases: ["SO_NO_MAP"] },
      { column: "brand", type: "text" },
      { column: "style_ref", type: "text" },
      { column: "shipment_date", type: "date" },
    ],
  },
  {
    sheetName: "mt_so_base",
    tableName: "o2.raw_mt_so_base",
    columns: [
      { column: "ou_code", type: "text" },
      { column: "so_year", type: "text" },
      { column: "so_no", type: "text" },
      { column: "so_no_doc", type: "text" },
      { column: "sea_code", type: "text" },
      { column: "cus_season", type: "text" },
      { column: "order_type", type: "text" },
      { column: "style_code", type: "text" },
      { column: "style_ref", type: "text" },
      { column: "gmt_type", type: "text" },
      { column: "score", type: "numeric" },
      { column: "score_gmt", type: "numeric" },
      { column: "sam", type: "numeric" },
      { column: "sam_gmt", type: "numeric" },
      { column: "post_status", type: "text" },
      { column: "exc_rate", type: "numeric" },
      { column: "vi", type: "text" },
      { column: "shipment_date", type: "date" },
      { column: "cust_code", type: "text" },
      { column: "cust_name", type: "text" },
      { column: "brand_code", type: "text" },
      { column: "brand_name", type: "text" },
      { column: "so_no_doc_ref", type: "text" },
    ],
  },
  {
    sheetName: "Refresh Date",
    tableName: "o2.raw_refresh_date",
    columns: [{ column: "refresh_date", type: "date" }],
  },
  {
    sheetName: "SortTable",
    tableName: "o2.raw_sort_table",
    columns: [
      { column: "sort_name", type: "text", sourceAliases: ["sortname"] },
      { column: "sort_order_value2", type: "numeric" },
    ],
  },
];
